# main.yml

name: 'main'

on:
  push:
    branches:
    - $default-branch

jobs:
  main:
    name: main
    runs-on: ubuntu-20.04

    defaults:
      shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner.
    - name: Checkout
      uses: actions/checkout@v2

    # Initialize the environment.
    - name: Init
      run: |
        # add the hashicorp apt repository
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

        # install required packages
        sudo apt update
        sudo apt install --yes terraform wireguard-tools

        # todo 27/06/2021: install age
