# main.yml

name: 'main'

on:
  push:
    branches:
    - master

jobs:
  main:
    name: main
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner.
    - name: Checkout
      uses: actions/checkout@v2

    # Initialize the environment.
    - name: Init
      env:
        AGE_VERSION: v1.0.0-rc.3
      run: |
        # add the hashicorp apt repository
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

        # install required packages
        sudo apt update
        sudo apt install --yes terraform wireguard-tools

        # install age
        curl -fsSLO https://github.com/FiloSottile/age/releases/download/${AGE_VERSION}/age-${AGE_VERSION}-linux-amd64.tar.gz
        tar xf age-${AGE_VERSION}-linux-amd64.tar.gz
        sudo mv age/age /usr/local/bin/age
        sudo mv age/age-keygen /usr/local/bin/age-keygen
        rm age-${AGE_VERSION}-linux-amd64.tar.gz
        printf "%s\n" "age $(age --version)"
        printf "%s\n" "age-keygen $(age-keygen --version)"

    # Put secrets in their proper place.
    - name: Secrets
      env:
        AGE_PRIVATE_KEY: ${{ secrets.AGE }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH }}
        WG_PRIVATE_KEY: ${{ secrets.PRIVATEKEY }}
        WG0_CONF: ${{ secrets.WG0 }}
      run: |
        mkdir -p ~/.age
        printf "%s" "${AGE_PRIVATE_KEY}" | tee ~/.age/key >/dev/null
        chmod 400 ~/.age/key

        mkdir -p ~/.ssh
        printf "%s" "${SSH_PRIVATE_KEY}" | tee ~/.ssh/id_ed25519 >/dev/null
        chmod 400 ~/.ssh/id_ed25519

        sudo mkdir -p /etc/wireguard
        printf "%s" "${WG_PRIVATE_KEY}" | sudo tee /etc/wireguard/privatekey >/dev/null
        printf "%s" "${WG0_CONF}" | sudo tee /etc/wireguard/wg0.conf >/dev/null
        sudo chmod -R 400 /etc/wireguard

    # Connect to the VPN of the server.
    - name: Connect to the VPN
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
      run: |
        sudo systemctl enable --now wg-quick@wg0
        ping -c 10 ${SERVER_IP}
