# main.yml

name: 'main'

on:
  push:
    branches:
    - master

jobs:
  main:
    name: main
    runs-on: ubuntu-20.04

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner.
    - name: Checkout
      uses: actions/checkout@v2

    # Initialize the environment.
    - name: Init
      run: |
        # add the hashicorp apt repository
        curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
        sudo apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

        # install required packages
        sudo apt update
        sudo apt install --yes terraform wireguard-tools

        # fixme 28/06/2021: hardcoded age version
        curl -fsSLO https://github.com/FiloSottile/age/releases/download/v1.0.0-rc.3/age-v1.0.0-rc.3-linux-amd64.tar.gz
        tar xf age-v1.0.0-rc.3-linux-amd64.tar.gz
        sudo mv age/age /usr/local/bin/age
        sudo mv age/age-keygen /usr/local/bin/age-keygen
        rm age-v1.0.0-rc.3-linux-amd64.tar.gz
        printf "%s\n" "age $(age --version)"
        printf "%s\n" "age-keygen $(age-keygen --version)"
